apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: climate-tls
  namespace: climate
spec:
  secretName: climate-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: tophe.me
  dnsNames:
  - tophe.me
  - www.tophe.me
