---
apiVersion: v1
kind: Service
metadata:
  name: climate-monitor-app-service
  namespace: climate
spec:
  type: ClusterIP
  selector:
    app: climate-monitor-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080