---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: front-end
  namespace: climate
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: climate-monitor-app
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
